export const testData = [
    {
        "name": "Гъби 500гр",
        "quantity": 1,
        "price": 2.19,
        "finalPrice": 2.19,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Bros изпарител 16бр",
        "quantity": 1,
        "price": 10.79,
        "finalPrice": 10.79,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Фикс 40г",
        "quantity": 1,
        "price": 1.59,
        "finalPrice": 1.59,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "spices",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Galaxy какао",
        "quantity": 1,
        "price": 1.19,
        "finalPrice": 1.19,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Derby 3л",
        "quantity": 1,
        "price": 1.19,
        "finalPrice": 1.19,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "drincs",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Добрудж. олио 1л",
        "quantity": 1,
        "price": 5.29,
        "finalPrice": 5.29,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "sunflower oil",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Кашкавал краве мл.",
        "quantity": 0.546,
        "price": 14.99,
        "finalPrice": 8.18454,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "cheese",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Devin мин вода 0,5",
        "quantity": 1,
        "price": 0.68,
        "finalPrice": 0.68,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Нистантни спагети 75г",
        "quantity": 2,
        "price": 0.75,
        "finalPrice": 1.5,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Fines без браш 300",
        "quantity": 1,
        "price": 2.29,
        "finalPrice": 2.29,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "bread",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Picantina риган",
        "quantity": 1,
        "price": 0.55,
        "finalPrice": 0.55,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "spices",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Фреско Ароматизатор",
        "quantity": 1,
        "price": 1.69,
        "finalPrice": 1.69,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "car",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Олио 1л",
        "quantity": 1,
        "price": 4.99,
        "finalPrice": 4.99,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "sunflower oil",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "KLC Мосса кафе 100г",
        "quantity": 1,
        "price": 4.79,
        "finalPrice": 4.79,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Спагети №5 500г",
        "quantity": 4,
        "price": 1.75,
        "finalPrice": 7,
        "shop": "Кауфленд",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Киселе мляко OLYMPUS 3,6%, 40",
        "quantity": 1,
        "price": 0.95,
        "finalPrice": 0.95,
        "shop": "Т-маркет",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Бисквити MULTICAKE какаов кре. 180г",
        "quantity": 1,
        "price": 1.29,
        "finalPrice": 1.29,
        "shop": "Т-маркет",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Мини вафли VINCINI какао 250",
        "quantity": 1,
        "price": 2.99,
        "finalPrice": 2.99,
        "shop": "Т-маркет",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Енергийна нап. Monster Abc. Z 500ml",
        "quantity": 1,
        "price": 1.79,
        "finalPrice": 1.79,
        "shop": "Т-маркет",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Лаваш Дина Традиционен 6бр, 270г",
        "quantity": 1,
        "price": 2.49,
        "finalPrice": 2.49,
        "shop": "Т-маркет",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    },
    {
        "name": "Маслини Услу натурални, кг",
        "quantity": 0.338,
        "price": 6.9,
        "finalPrice": 2.3322000000000003,
        "shop": "Т-маркет",
        "storeCode": "",
        "barcode": "",
        "keyword": "",
        "date": "Date(2022,6,2)",
        "iso": "BGN"
    }
]